# Generated by Django 4.2.3 on 2023-08-16 16:08

import django.db.models.deletion
import tasksapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offerapp", "0001_initial"),
        ("usersapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("realization_time", models.DateField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "open"),
                            (1, "on-hold"),
                            (2, "on-going"),
                            (3, "objections"),
                            (4, "completed"),
                            (5, "cancelled"),
                        ],
                        default=0,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "selected_offer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_task",
                        to="offerapp.offer",
                    ),
                ),
                ("skills", models.ManyToManyField(to="usersapp.skill")),
            ],
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attachment", models.FileField(upload_to=tasksapp.models.get_upload_path)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="tasksapp.task"
                    ),
                ),
            ],
        ),
    ]
