# Generated by Django 4.2.8 on 2024-01-14 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="days_to_complete",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="offer",
            name="realization_time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
