# Generated by Django 4.2.4 on 2023-09-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasksapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complainant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints_made",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="arbiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints_to_judge",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(fields=("task", "complainant"), name="unique_task_user"),
        ),
    ]
