# Generated by Django 4.2.10 on 2024-04-22 12:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usersapp", "0001_initial"),
        ("tasksapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="accepted"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="budget"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="contractor"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="days_to_complete",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="days to complete"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="tasksapp.payment",
                verbose_name="payment",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="realization_time",
            field=models.DateField(blank=True, null=True, verbose_name="realization time"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="solution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer",
                to="tasksapp.solution",
                verbose_name="solution",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="tasksapp.task",
                verbose_name="task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="budget"),
        ),
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="client"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="task",
            name="days_to_complete",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)], verbose_name="days to complete"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="selected_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_task",
                to="tasksapp.offer",
                verbose_name="selected offer",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="skills",
            field=models.ManyToManyField(to="usersapp.skill", verbose_name="skills"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "open"),
                    (1, "on-hold"),
                    (2, "on-going"),
                    (3, "objections"),
                    (4, "completed"),
                    (5, "cancelled"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=120, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
