# Generated by Django 4.2.8 on 2024-01-14 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0002_alter_offer_days_to_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="days_to_complete",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
