# Generated by Django 4.2.2 on 2023-08-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerapp", "0001_initial"),
        ("tasksapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="offers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task",
                to="offerapp.offer",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="selected_offer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_task",
                to="offerapp.offer",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "open"),
                    (1, "on-hold"),
                    (2, "on-going"),
                    (3, "objections"),
                    (4, "completed"),
                    (5, "cancelled"),
                ],
                default=0,
            ),
        ),
    ]
