# Generated by Django 4.2.3 on 2023-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersapp", "0002_alter_rating_code_quality_alter_rating_contact_and_more"),
        ("tasksapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="skills",
            field=models.ManyToManyField(to="usersapp.skill"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "open"),
                    (1, "on-hold"),
                    (2, "on-going"),
                    (3, "objections"),
                    (4, "completed"),
                    (5, "cancelled"),
                ],
                default=0,
            ),
        ),
    ]
