# Generated by Django 4.2.10 on 2024-05-07 19:58

import django.db.models.deletion
import tasksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasksapp", "0002_alter_offer_accepted_alter_offer_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintattachment",
            name="attachment",
            field=models.FileField(upload_to=tasksapp.models.get_upload_path, verbose_name="attachment"),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tasksapp.complaint",
                verbose_name="complaint",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="solutionattachment",
            name="attachment",
            field=models.FileField(upload_to=tasksapp.models.get_upload_path, verbose_name="attachment"),
        ),
        migrations.AlterField(
            model_name="solutionattachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="solutionattachment",
            name="solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tasksapp.solution",
                verbose_name="solution",
            ),
        ),
        migrations.AlterField(
            model_name="solutionattachment",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="attachment",
            field=models.FileField(upload_to=tasksapp.models.get_upload_path, verbose_name="attachment"),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tasksapp.task",
                verbose_name="task",
            ),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
