# Generated by Django 4.2.2 on 2023-08-13 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0003_task_offers_task_selected_offer_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="offers",
        ),
        migrations.RemoveField(
            model_name="task",
            name="selected_offer",
        ),
    ]
