# Generated by Django 4.2.2 on 2023-08-13 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0003_task_skills_alter_task_status"),
        ("tasksapp", "0004_remove_task_offers_remove_task_selected_offer"),
    ]

    operations = []
