# Generated by Django 4.2.2 on 2023-08-13 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0005_merge_20230813_1351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="skills",
        ),
    ]
