# Generated by Django 4.2.2 on 2023-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersapp", "0002_alter_rating_code_quality_alter_rating_contact_and_more"),
        ("tasksapp", "0006_remove_task_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="skills",
            field=models.ManyToManyField(to="usersapp.skill"),
        ),
    ]
