# Generated by Django 4.2.2 on 2023-08-13 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerapp", "0003_alter_offer_budget"),
        ("tasksapp", "0007_task_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="selected_offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_task",
                to="offerapp.offer",
            ),
        ),
    ]
