# Generated by Django 4.2.10 on 2024-04-24 17:38

import django.core.validators
import django.db.models.deletion
import usersapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usersapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockeduser",
            name="blocked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blocked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="blocked user",
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocking_end_date",
            field=models.DateTimeField(verbose_name="blocking end date"),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocking_start_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="blocking start date"),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocking_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blocking",
                to=settings.AUTH_USER_MODEL,
                verbose_name="blocking user",
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="reason",
            field=models.TextField(verbose_name="reason"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.CharField(max_length=150, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="code_quality",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="code quality",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="contact",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="solution_time",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="solution time",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill",
            field=models.CharField(max_length=40, unique=True, verbose_name="skill"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=usersapp.models.get_profile_picture_path,
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(to="usersapp.skill", verbose_name="skills"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
