# Generated by Django 4.2.10 on 2024-03-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockeduser",
            name="full_blocking",
            field=models.BooleanField(default=False),
        ),
    ]
