# Generated by Django 4.2.10 on 2024-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_blockeduser_full_blocking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockeduser",
            name="blocking_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
