version: '3.9'
name: stock-market
services:
  app:
    build:
      context: ../../../
      dockerfile: ./src/deployment/local/Dockerfile
    container_name: "stock-market-app"
    volumes:
      - static:/app/static
      - media:/app/media
      - ../../psmproject/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
  worker:
    build:
      context: ../../../
      dockerfile: ./src/deployment/local/Dockerfile
    container_name: "stock-market-worker"
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    command: ['celery', '-A', 'psmproject.celery', 'worker', '-l', 'info']
    depends_on:
      app:
        condition: service_healthy
  redis:
    image: "redis:latest"
    volumes:
      - redis-data:/data
    expose:
      - 6379
  db:
    image: postgres:13
    container_name: "stock-market-db"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data/:Z
    expose:
      - 5432

volumes:
  static:
  media:
  redis-data:
  db-data:
