# Generated by Django 4.2.3 on 2023-08-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(fields=("chat", "user"), name="unique_user_in_chat"),
        ),
    ]
