# Generated by Django 4.2.3 on 2023-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0003_alter_message_content"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                check=models.Q(("role__in", ["CL", "CO", "AR", "MO"])), name="chatapp_participant_role_valid"
            ),
        ),
    ]
