# Generated by Django 4.2.3 on 2023-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0004_participant_chatapp_participant_role_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("CL", "Client"), ("CO", "Contractor"), ("AR", "Arbiter"), ("MO", "Moderator")],
                max_length=2,
                null=True,
            ),
        ),
    ]
