name: stock-market
services:
  app:
    build:
      context: ../../../
      dockerfile: ./src/deployment/mikrus/Dockerfile
    container_name: "stock-market-app"
    command: /start-app
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 180s
    networks:
      - network_back
      - network_front
  websocket:
    build:
      context: ../../../
      dockerfile: ./src/deployment/mikrus/Dockerfile
    container_name: "stock-market-websocket"
    command: /start-websocket
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      app:
        condition: service_healthy
    networks:
      - network_back
      - network_front
  worker:
    build:
      context: ../../../
      dockerfile: ./src/deployment/mikrus/Dockerfile
    container_name: "stock-market-worker"
    command: /start-worker
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      app:
        condition: service_healthy
    networks:
      - network_back
      - network_front
  redis:
    image: "redis:latest"
    volumes:
      - redis-data:/data
    expose:
      - "${REDIS_PORT}"
    networks:
      - network_back
  db:
    image: postgres:13
    container_name: "stock-market-db"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data/:Z
    expose:
      - 5432
    networks:
      - network_back
  nginx:
    build:
      context: ../../
      dockerfile: ./deployment/mikrus/nginx/Dockerfile
    container_name: "stock-market-nginx"
    environment:
      - APP_HOST=stock-market-app
      - APP_PORT=8000
      - WS_HOST=stock-market-websocket
      - WS_PORT=8001
      - PORT=80
    volumes:
      - static:/home/app/web/staticfiles
      - media:/home/app/web/mediafiles
    ports:
      - "${IP4_PORT}:80"
      - "[::]:80:80"
    networks:
      - ip6net
      - network_back
    depends_on:
      app:
        condition: service_healthy
volumes:
  static:
  media:
  redis-data:
  db-data:

networks:
  network_front:
    driver: bridge
    name: stock-market-front
  network_back:
    driver: bridge
    internal: true
    name: stock-market-back
  ip6net:
    enable_ipv6: true
    name: stock-market-ip6
    ipam:
      config:
        - subnet: "fd4a:5a20:acde:cafe::/64"
