from django.urls import path

from .views import (
    arbiter,
    attachment,
    client,
    common,
    contractor,
    moderator_offers,
    moderator_solutions,
    moderator_tasks,
)

urlpatterns = [
    path("", client.TasksCurrentListView.as_view(), name="tasks-client-list"),
    path(
        "history/",
        client.TasksHistoricalListView.as_view(),
        name="tasks-client-history-list",
    ),
    path("moderator/", moderator_tasks.TasksListView.as_view(), name="tasks-moderator-list"),
    path("contractor/closed/", contractor.TasksClosedListView.as_view(), name="tasks-contractor-closed-list"),
    path("contractor/", contractor.TasksListView.as_view(), name="tasks-contractor-list"),
    path("moderator/new/", moderator_tasks.TasksNewListView.as_view(), name="tasks-moderator-list-new"),
    path("add/", client.TaskCreateView.as_view(), name="task-create"),
    path("<pk>/preview", common.TaskPreviewView.as_view(), name="task-preview"),
    path("<pk>/delete", common.TaskDeleteView.as_view(), name="task-delete"),
    path("<pk>/edit", client.TaskEditView.as_view(), name="task-edit"),
    path(
        "<pk>/moderator/edit",
        moderator_tasks.TaskEditView.as_view(),
        name="task-moderator-edit",
    ),
    path(
        "<pk>/moderator",
        moderator_tasks.TaskDetailView.as_view(),
        name="task-moderator-detail",
    ),
    path(
        "<pk>/contractor",
        contractor.TaskContractorDetailView.as_view(),
        name="task-contractor-detail",
    ),
    path(
        "<pk>/add_attachment",
        attachment.TaskAttachmentAddView.as_view(),
        name="task-add-attachment",
    ),
    path("<pk>", common.TaskDetailView.as_view(), name="task-detail"),
    path(
        "attachment/<pk>/delete",
        attachment.TaskAttachmentDeleteView.as_view(),
        name="task-attachment-delete",
    ),
    path("attachment/<pk>/download", attachment.download, name="task-attachment-download"),
    path("offers/", contractor.OfferListView.as_view(), name="offers-list"),
    path("offers/moderator/", moderator_offers.OfferListView.as_view(), name="offer-moderator-list"),
    path("offers/moderator/new", moderator_offers.OfferNewListView.as_view(), name="offer-moderator-list-new"),
    path("offer/add/task/<task_pk>", contractor.OfferCreateView.as_view(), name="offer-create"),
    path("offer/task-search", contractor.TasksSearchView.as_view(), name="offer-task-search"),
    path("offer/moderator/<pk>", moderator_offers.OfferDetailView.as_view(), name="offer-moderator-detail"),
    path("offer/moderator/<pk>/edit", moderator_offers.OfferEditView.as_view(), name="offer-moderator-edit"),
    path("offer/<pk>", contractor.OfferDetailView.as_view(), name="offer-detail"),
    path("offer/<pk>/delete", contractor.OfferDeleteView.as_view(), name="offer-delete"),
    path("offer/<pk>/edit", contractor.OfferEditView.as_view(), name="offer-edit"),
    path("offers/client/", client.OfferClientListView.as_view(), name="offers-client-list"),
    path("<pk>/offers/", client.TaskOfferClientListView.as_view(), name="task-offers-list"),
    path("offers/client/<pk>", client.OfferClientAcceptView.as_view(), name="offer-client-accept"),
    path("complaint/add/task/<task_pk>", common.ComplaintCreateView.as_view(), name="complaint-create"),
    path("complaint/<pk>", common.ComplaintDetailView.as_view(), name="complaint-detail"),
    path("complaint/<pk>/edit", common.ComplaintEditView.as_view(), name="complaint-edit"),
    path("complaint/<pk>/delete", common.ComplaintDeleteView.as_view(), name="complaint-delete"),
    path("solution/add/offer/<offer_pk>", contractor.SolutionCreateView.as_view(), name="solution-create"),
    path("solution/<pk>", contractor.SolutionDetailView.as_view(), name="solution-detail"),
    path("solution/<pk>/edit", contractor.SolutionEditView.as_view(), name="solution-edit"),
    path("solution/<pk>/delete", contractor.SolutionDeleteView.as_view(), name="solution-delete"),
    path("solution/<pk>/accept", client.SolutionClientAcceptView.as_view(), name="solution-accept"),
    path("solutions/moderator/", moderator_solutions.SolutionListView.as_view(), name="solutions-moderator-list"),
    path(
        "solutions/moderator/new/",
        moderator_solutions.SolutionNewListView.as_view(),
        name="solutions-moderator-list-new",
    ),
    path("solution/moderator/<pk>", moderator_solutions.SolutionDetailView.as_view(), name="solution-moderator-detail"),
    path(
        "solution/moderator/<pk>/edit", moderator_solutions.SolutionEditView.as_view(), name="solution-moderator-edit"
    ),
    path("complaint/arbiter/", arbiter.ComplaintListView.as_view(), name="complaint-arbiter-list"),
    path("complaint/arbiter/new/", arbiter.ComplaintNewListView.as_view(), name="complaint-arbiter-list-new"),
    path("complaint/arbiter/active/", arbiter.ComplaintActiveListView.as_view(), name="complaint-arbiter-list-active"),
    path("complaint/arbiter/take/<pk>", arbiter.ComplaintTakeView.as_view(), name="complaint-arbiter-take"),
    path("complaint/arbiter/close/<pk>", arbiter.ComplaintCloseView.as_view(), name="complaint-arbiter-close"),
    path("complaint/arbiter/<pk>", arbiter.ComplaintDetailView.as_view(), name="complaint-arbiter-detail"),
]
