# Generated by Django 4.2.4 on 2023-08-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offerapp", "0001_initial"),
        ("tasksapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="task", to="tasksapp.task"
            ),
        ),
    ]
