# Generated by Django 4.2.2 on 2023-08-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0004_remove_task_offers_remove_task_selected_offer"),
        ("offerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="task", to="tasksapp.task"
            ),
        ),
    ]
