# Generated by Django 4.2.4 on 2023-09-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="solution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer",
                to="offerapp.solution",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="submitted",
            field=models.BooleanField(default=True),
        ),
    ]
