# Generated by Django 4.2.2 on 2023-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerapp", "0002_offer_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
