name: Python Code Quality and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy-django-plugin django-stubs
        pip install flake8 isort black mypy autoflake
    - name: Run Flake8
      run: |
        flake8
    - name: Run isort
      run: |
        isort . --check --diff
    - name: Run black
      run: |
        black . --check
    - name: Run mypy
      run: |
        mypy .
    - name: Run autoflake
      run: |
        autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place app --exclude=__init__.py
