name: Django Test Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install poetry 1.5
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry>=1.5.1,<1.6

    - name: Install Dependencies
      run: |
        python -m poetry install --with dev

    - name: Run Tests
      run: |
        python src/psmproject/manage.py test
